    - name: Update repositories cache and install "httpd" package
      ansible.builtin.package:
        name: httpd
        update_cache: yes
        state: present
      become: yes

    - name: enable service httpd and ensure it is not masked
      systemd:
        name: httpd
        enabled: yes
        masked: no
      become: yes

    - name: start httpd
      ansible.builtin.systemd:
        state: started
        name: httpd
      become: yes