---
- hosts: all
  gather_facts: yes
  tasks:
    - include_tasks: universal/setup.yaml
    - include_tasks: centos/httpd.yaml
      when: ansible_facts['os_family'] == "RedHat"
    - include_tasks: debian/apache.yaml
      when: ansible_facts['os_family'] == "Debian"
