  - name: instal epel on RHEL
    ansible.builtin.package:
      name: epel-release
      update_cache: true
      state: present
    become: true
    when: ansible_facts['os_family'] == "RedHat"

  - name: install setuptools
    pip:
      name: setuptools

  - name: pip self-update
    shell: "pip install --upgrade pip"
    become: true

  - name: Install Python pip
    ansible.builtin.package:
      name: "{{ item }}"
      update_cache: true
      state: present
    with_items:
    - python-pip
    - python3-pip
    become: true